/* 行程数据：土耳其 TR、希腊 GR、路线节点 NODES */
const TR=[
 {id:"d6",d:6,w:"周五",t:"悉尼（Sydney）出发",
  img:[["Sydney Airport","悉尼机场（Sydney Airport, SYD）"],["Sydney","悉尼（Sydney）"],["Istanbul Airport","伊斯坦布尔机场（İstanbul Havalimanı, IST）"]],
  plan:[["白天","收拾行李，6 人 6 个大箱先称一遍"],["18:30","SYD T1 办票、托运"],["21:30","✈ EY455 悉尼 → 阿布扎比"]],
  redeye:"机上（EY455 悉尼 → 阿布扎比）"},
 {id:"d7",d:7,w:"周六",t:"伊斯坦布尔（Istanbul），抵达",
  img:[["Hagia Sophia","圣索菲亚大教堂（Ayasofya）"],["Sultan Ahmed Mosque","蓝色清真寺（Sultanahmet Camii）"],["Hippodrome of Constantinople","竞技场（Hippodrome / At Meydanı）"]],
  plan:[["08:45","✈ EY541 阿布扎比 → 伊斯坦布尔"],["12:50","落地 IST，到老城酒店寄存行李"],["15:00","圣索菲亚（Ayasofya）"],["16:30","蓝色清真寺、竞技场（Hippodrome），日落约 17:50"]],
  stay:"伊斯坦布尔（Istanbul）"},
 {id:"d8",d:8,w:"周日",t:"博斯普鲁斯海峡（Bosphorus）",
  img:[["Bosphorus","博斯普鲁斯海峡（Boğaziçi）",{src:"images/11-08/Bosphorus-Klook.jpg",credit:"Klook"}],["Dolmabahçe Palace","多尔玛巴赫切宫（Dolmabahçe Sarayı）"],["Galata Tower","加拉塔塔（Galata Kulesi）"]],
  plan:[["上午","海峡游船"],["下午","多尔玛巴赫切宫、奥塔科伊（Ortaköy）"],["傍晚","加拉塔塔、卡拉科伊（Karaköy）"]],
  stay:"伊斯坦布尔（Istanbul）"},
 {id:"d9",d:9,w:"周一",t:"老城宫殿与市集",
  img:[["Topkapı Palace","托普卡帕宫（Topkapı Sarayı）"],["Basilica Cistern","地下水宫（Yerebatan Sarnıcı）"],["Grand Bazaar, Istanbul","大巴扎（Kapalıçarşı）"],["Süleymaniye Mosque","苏莱曼尼耶清真寺（Süleymaniye Camii）"]],
  plan:[["上午","托普卡帕宫、地下水宫（Yerebatan Sarnıcı）"],["中午","埃米诺努（Eminönü）午餐"],["下午","大巴扎、香料市场（Mısır Çarşısı）、苏莱曼尼耶清真寺"],["傍晚","金角湾（Haliç）"]],
  stay:"伊斯坦布尔（Istanbul）"},
 {id:"d10",d:10,w:"周二",t:"飞往卡帕多奇亚（Kapadokya）",
  img:[["Uçhisar","乌奇希萨尔城堡（Uçhisar Kalesi）"],["Göreme","格雷梅小镇（Göreme）"],["Fairy chimney","精灵烟囱（Peribacaları）"]],
  plan:[["上午","✈ 伊斯坦布尔 → ASR / NAV"],["下午","入住格雷梅（Göreme）或乌奇希萨尔（Uçhisar）"],["傍晚","观景点看日落"]],
  stay:"卡帕多奇亚（Kapadokya）"},
 {id:"d11",d:11,w:"周三",t:"热气球日出",
  img:[["Cappadocia","热气球与岩谷"],["Göreme Open Air Museum","格雷梅露天博物馆（Göreme Açık Hava Müzesi）"],["Göreme National Park","格雷梅国家公园（Göreme Milli Parkı）"]],
  plan:[["日出","观景点拍热气球（不乘坐）"],["上午","格雷梅露天博物馆"],["下午","乌奇希萨尔（Uçhisar）、帕夏贝（Paşabağ）、泽尔韦（Zelve）选 2–3 个"]],
  stay:"卡帕多奇亚（Kapadokya）"},
 {id:"d12",d:12,w:"周四",t:"飞回伊斯坦布尔（Istanbul），开往恰纳卡莱（Çanakkale）",
  img:[["1915 Çanakkale Bridge","1915 恰纳卡莱大桥（1915 Çanakkale Köprüsü）"],["Istanbul Airport","伊斯坦布尔机场（İstanbul Havalimanı, IST）"],["Çanakkale","恰纳卡莱海滨的特洛伊木马（Trojan Horse, Çanakkale）",{src:"images/Çanakkale-trojan-horse.webp",credit:"Dreamstime（预览水印）"}]],
  plan:[["上午","✈ 回 IST，机场取车"],["下午","🚗 IST → 恰纳卡莱，约 3.5 小时"],["晚上","海滨散步、晚餐"]],
  stay:"恰纳卡莱（Çanakkale）"},
 {id:"d13",d:13,w:"周五",t:"特洛伊（Troy）+ 帕加马（Pergamon）",
  img:[["Troy","特洛伊遗址（Troya）"],["Troy Museum","特洛伊博物馆（Troya Müzesi）"],["Pergamon","帕加马卫城（Pergamon Akropolisi）"]],
  plan:[["上午","🚗 恰纳卡莱 → 特洛伊，约 30 分钟；遗址 + 博物馆"],["下午","🚗 到贝尔加马（Bergama），约 2.5–3 小时；帕加马卫城"],["晚上","🚗 到伊兹密尔（İzmir），约 1.5 小时"]],
  tip:"全程最累的一天，有时间增加 Asklepion",stay:"伊兹密尔（İzmir）"},
 {id:"d14",d:14,w:"周六",t:"以弗所（Ephesus）一日游",
  img:[["Library of Celsus","塞尔苏斯图书馆（Library of Celsus）"],["Ephesus","以弗所古城（Efes）"],["Şirince","希林杰村（Şirince）"]],
  plan:[["上午","🚗 伊兹密尔 → 塞尔丘克（Selçuk），约 1 小时"],["白天","塞尔苏斯图书馆、大剧场（Great Theatre）、库雷特斯街（Curetes Street）"],["下午","可选：以弗所博物馆（Efes Müzesi）、阿尔忒弥斯神庙（Temple of Artemis）、希林杰（Şirince）"]],
  stay:"伊兹密尔（İzmir）"},
 {id:"d15",d:15,w:"周日",t:"伊兹密尔（İzmir）→ 雅典（Athens）",
  img:[["İzmir Clock Tower","科纳克钟楼（İzmir Saat Kulesi）"],["İzmir","科尔顿海滨（Kordon）"],["Kemeraltı","凯梅拉尔特市集（Kemeraltı）"]],
  plan:[["上午","科尔顿海滨（Kordon）、科纳克钟楼（Konak）、凯梅拉尔特（Kemeraltı）"],["下午","ADB 机场还车"],["晚上","✈ 20:40 伊兹密尔 → 雅典（直飞）"]],
  note:["伊兹密尔（ADB）→ 雅典（ATH）有直飞，11/13 与 11/15 各一班，都是 20:40 起飞 / 20:40 落地——飞行约 1 小时，而土耳其比希腊早 1 小时，所以钟点看着没动。",
        "按现行行程订 11/15 这班：白天逛科尔顿和凯梅拉尔特，下午 ADB 还车，晚上飞，取完行李 21:30 前后进雅典市区。",
        "11/13 那班要砍掉以弗所（11/14）才用得上；两班都订不到就退回经伊斯坦布尔转机。"],
  stay:"雅典（Athens）"}
];
const GR=[
 {id:"d16",d:16,w:"周一",t:"雅典卫城（Acropolis）",
  img:[["Parthenon","帕特农神庙（Parthenon）"],["Acropolis Museum","卫城博物馆内部（Inside the Acropolis Museum）",{src:"images/arc-mesuem.webp",credit:"Marco Argüello for Lonely Planet"}],["Temple of Hephaestus","赫菲斯托斯神庙（Temple of Hephaestus）"]],
  plan:[["上午","卫城：帕特农、伊瑞克提翁神庙（Erechtheion）"],["下午","卫城博物馆 → 古市集（Ancient Agora）"],["傍晚","普拉卡（Plaka）、莫纳斯提拉基（Monastiraki）"]],
  stay:"雅典（Athens）"},
 {id:"d17",d:17,w:"周二",t:"雅典（Athens）自由日",
  img:[["Panathenaic Stadium","帕纳辛奈克体育场（Panathenaic Stadium）"],["National Archaeological Museum, Athens","国家考古博物馆（National Archaeological Museum）"],["Mount Lycabettus","利卡维多斯山（Lycabettus）"]],
  plan:[["白天","国家考古博物馆或帕纳辛奈克体育场"],["傍晚","利卡维多斯山看日落"],["晚上","准备自驾"]],
  stay:"雅典（Athens）"},
 {id:"d18",d:18,w:"周三",t:"雅典（Athens）→ 德尔斐（Delphi）",
  img:[["Delphi","德尔斐遗址（Delphi）"],["Temple of Apollo (Delphi)","阿波罗神庙（Temple of Apollo）"],["Tholos of Delphi","雅典娜圣域圆形神殿（Tholos）"]],
  plan:[["上午","雅典取车，🚗 约 2.5 小时"],["下午","阿波罗神庙、古剧场（Ancient Theatre）、雅典娜圣域（Athena Pronaia）"],["另","德尔斐考古博物馆（Delphi Archaeological Museum）"]],
  stay:"德尔斐（Delphi）"},
 {id:"d19",d:19,w:"周四",t:"德尔斐（Delphi）→ 约阿尼纳（Ioannina）",
  img:[["Ioannina","约阿尼纳（Ioannina）"],["Lake Pamvotida","帕姆沃蒂斯湖（Lake Pamvotida）"],["Ioannina Castle","约阿尼纳城堡（Ioannina Castle）"],["Zagori","扎戈里山区（Zagori / Ζαγόρι）"]],
  plan:[["上午","🚗 约 4–4.5 小时"],["下午","湖畔"],["傍晚","城堡与老城"]],
  note:["住宿可以换成扎戈里（Zagori / Ζαγόρι）的石屋民宿——莫诺登德里（Monodendri）、维察（Vitsa）、阿里斯提（Aristi）、帕皮戈（Papigo）一带，离约阿尼纳 45–75 分钟山路。这样 11/20 早上人已经在山里，省掉一趟往返。",
        "代价是今天下午要压缩：德尔斐 8:30 出发 → 约阿尼纳 13:00 → 湖畔与城堡 13:30–15:15 → 趁天亮上山（日落约 17:15）。山路夜里不好开，这一段务必留在白天。",
        "6 人要 3 间房，山村民宿多只有 5–10 间；11 月是淡季，部分民宿和餐馆歇业，先订好并确认开门。石板巷子窄，车停村口停车场，不要开进村心。"],
  stay:"约阿尼纳（Ioannina），或扎戈里山间民宿"},
 {id:"d20",d:20,w:"周五",t:"约阿尼纳（Ioannina）→ 迈泰奥拉（Meteora）",
  img:[["Meteora","迈泰奥拉（Meteora）"],["Vikos Gorge","维科斯峡谷（Vikos Gorge）"],["Kastraki","卡斯特拉基村（Kastraki）"],["Kalabaka","卡兰巴卡（Kalabaka）"]],
  plan:[["上午","🚗 扎戈里（Zagori）山区半日，或约阿尼纳补充"],["中午","🚗 约 2 小时到卡斯特拉基（Kastraki）"],["傍晚","观景点看日落"]],
  note:["上午去扎戈里完全来得及，而且不算回头路——扎戈里在约阿尼纳东北，上下山的路口（Karyes）本来就在去迈泰奥拉的 A2 高速上。",
        "半日线：约阿尼纳 8:00 出发 → 莫诺登德里（Monodendri）约 50 分钟 → 维科斯峡谷 Oxya 观景台 + Agia Paraskevi 修道院 1–1.5 小时 → 顺路看基皮（Kipoi）的石拱桥 → 14:00 前后到卡斯特拉基。莫诺登德里到卡兰巴卡约 2 小时 15 分，只比直接开多 20 分钟左右，赶日落（约 17:10）绰绰有余。",
        "想深入帕皮戈、弗拉德托台阶（Vradeto Steps）、Beloi 观景台要一整天，这趟塞不进来。11 月 1300 m 以上可能有雪或结冰，雾雨也常见；A2 走隧道穿过 Metsovo，不必翻 Katara 山口。"],
  stay:"卡斯特拉基（Kastraki）"},
 {id:"d21",d:21,w:"周六",t:"迈泰奥拉（Meteora）→ 雅典（Athens）",
  img:[["Monastery of Great Meteoron","大迈泰奥拉修道院（Great Meteoron）"],["Monastery of Varlaam","瓦尔拉姆修道院（Varlaam）"],["Monastery of Rousanou","鲁萨努修道院（Roussanou）"]],
  plan:[["上午","选 2–3 座修道院"],["下午","🚗 约 4–4.5 小时回雅典"],["晚上","还车"]],
  tip:"11 月修道院开放日临近出发再确认",stay:"雅典（Athens）"},
 {id:"d22",d:22,w:"周日",t:"返回悉尼（Sydney）",
  img:[["Plaka","普拉卡老街（Plaka）"],["Syntagma Square","宪法广场（Syntagma Square）"],["Athens International Airport","雅典机场（Athens Intl., ATH）"]],
  plan:[["09:30","早餐后离开酒店去 ATH"],["13:05","✈ EY190 雅典 → 阿布扎比"],["21:05","✈ EY454 阿布扎比 → 悉尼，11/23 17:45 落地"]],
  note:["回程在阿布扎比只停 1 小时 30 分（去程停 3 小时 45 分）。行李直挂悉尼，但 EY190 一旦延误这段就很紧，登机口之间别耽搁。"],
  redeye:"机上（EY454 阿布扎比 → 悉尼）"}
];
const NODES={
 tr:[{n:"悉尼出发",en:"Sydney",dt:"11/6",nt:"SYD → IST",to:"d6",pass:1,next:"fly"},
     {n:"伊斯坦布尔",en:"Istanbul",dt:"11/7 – 11/9",nt:"3 晚",to:"d7",next:"fly"},
     {n:"卡帕多奇亚",en:"Kapadokya",dt:"11/10 – 11/11",nt:"2 晚",to:"d10",next:"fly"},
     {n:"恰纳卡莱",en:"Çanakkale",dt:"11/12",nt:"1 晚",to:"d12"},
     {n:"特洛伊 · 帕加马",en:"Troya · Pergamon",dt:"11/13",nt:"途经",to:"d13",pass:1},
     {n:"伊兹密尔",en:"İzmir",dt:"11/13 – 11/14",nt:"2 晚",to:"d13"},
     {n:"以弗所",en:"Efes / Ephesus",dt:"11/14",nt:"一日游",to:"d14",pass:1,next:"fly"},
     {n:"飞往雅典",en:"Athens",dt:"11/15",nt:"ADB → ATH",to:"d15",pass:1}],
 gr:[{n:"雅典",en:"Athens",dt:"11/15 – 11/17",nt:"3 晚",to:"d16"},
     {n:"德尔斐",en:"Delphi",dt:"11/18",nt:"1 晚",to:"d18"},
     {n:"约阿尼纳",en:"Ioannina",dt:"11/19",nt:"1 晚",to:"d19"},
     {n:"迈泰奥拉",en:"Meteora",dt:"11/20",nt:"1 晚",to:"d20"},
     {n:"雅典",en:"Athens",dt:"11/21",nt:"1 晚",to:"d21",next:"fly"},
     {n:"回悉尼",en:"Sydney",dt:"11/22",nt:"ATH → SYD",to:"d22",pass:1}]
};
